# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./scripts/generate-db/package-lock.json
    - run: ls
    - run: npm install
      working-directory: scripts/generate-db
    - run: npm run generate
      working-directory: scripts/generate-db
    - run: npm test
    - name: Add & Commit
    # You may pin to the exact commit or the version.
    # uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b
      uses: EndBug/add-and-commit@v9.1.1
      with:
        # Arguments for the git add command
        add: .
        message: 'update db'
        new_branch: release
        push: 'origin release --force'
